package money.hejje.market.indicators;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import money.hejje.common.Timeframe;
import money.hejje.market.Candle;

/** Loads the golden CSV (generated by research/tools/gen_indicator_fixtures.py) into candles plus expected columns. */
final class Fixtures {

    static final ZoneId IST = ZoneId.of("Asia/Kolkata");
    static final UUID INSTRUMENT = UUID.fromString("00000000-0000-7000-8000-000000000001");

    record Row(Candle candle, Map<String, Double> expected) {}

    private Fixtures() {
    }

    static List<Row> golden() {
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(
                Fixtures.class.getResourceAsStream("/indicators/golden.csv"), StandardCharsets.UTF_8))) {
            String[] header = reader.readLine().split(",");
            List<Row> rows = new ArrayList<>();
            String line;
            while ((line = reader.readLine()) != null) {
                String[] cells = line.split(",", -1);
                Map<String, String> byName = new LinkedHashMap<>();
                for (int i = 0; i < header.length; i++) {
                    byName.put(header[i], cells[i]);
                }
                LocalDateTime ts = LocalDateTime.parse(byName.get("ts"));
                Candle candle = new Candle(INSTRUMENT, Timeframe.M5, ts.atZone(IST).toInstant(), new BigDecimal(byName.get("open")),
                        new BigDecimal(byName.get("high")), new BigDecimal(byName.get("low")), new BigDecimal(byName.get("close")),
                        Long.parseLong(byName.get("volume")), 0, false);
                Map<String, Double> expected = new LinkedHashMap<>();
                for (int i = 6; i < header.length; i++) {
                    expected.put(header[i], cells[i].isEmpty() ? Double.NaN : Double.parseDouble(cells[i]));
                }
                rows.add(new Row(candle, expected));
            }
            return rows;
        } catch (Exception e) {
            throw new IllegalStateException("Cannot read golden fixture", e);
        }
    }

    /** Builds a 5-minute candle at the given IST date-time. */
    static Candle candle(String istDateTime, String open, String high, String low, String close, long volume) {
        return new Candle(INSTRUMENT, Timeframe.M5, LocalDateTime.parse(istDateTime).atZone(IST).toInstant(), new BigDecimal(open),
                new BigDecimal(high), new BigDecimal(low), new BigDecimal(close), volume, 0, false);
    }
}
