#!/usr/bin/env python3
"""Generates config/universe/nifty500.yaml from NSE's ind_nifty500list.csv (plan M8.1).

Standard library only. Re-run at the semi-annual index reviews and commit the result:

    python3 research/tools/gen_universe.py                      # downloads the CSV and the Kite NSE instrument dump
    python3 research/tools/gen_universe.py --csv ind_nifty500list.csv --instruments nse.csv
    python3 research/tools/gen_universe.py --no-check           # skip the instrument master check

Symbols that are not in the instrument dump (renamed, suspended, a series other than EQ) are reported on stderr and
kept in the file: the server reports them again as unresolved when the universe is backfilled.
"""
import argparse
import csv
import datetime
import io
import sys
import urllib.request

NSE_CSV = "https://nsearchives.nseindia.com/content/indices/ind_nifty500list.csv"
KITE_NSE = "https://api.kite.trade/instruments/NSE"
OUT = "config/universe/nifty500.yaml"


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0", "Accept": "text/csv,*/*"})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read().decode("utf-8-sig")


def read(path_or_none, url):
    if path_or_none:
        with open(path_or_none, encoding="utf-8-sig") as f:
            return f.read()
    return fetch(url)


def constituents(text):
    rows = []
    for row in csv.DictReader(io.StringIO(text)):
        row = {k.strip(): (v or "").strip() for k, v in row.items()}
        if row.get("Symbol"):
            rows.append((row["Symbol"], row["Industry"], row.get("Series", "")))
    return sorted(rows)


def tradable(text):
    return {row["tradingsymbol"] for row in csv.DictReader(io.StringIO(text)) if row.get("instrument_type") == "EQ"}


def render(rows, today):
    lines = [
        "# NIFTY 500 constituents with NSE's industry per symbol: the daily (D1) universe of ratings, bases and analogs.",
        f"# Generated by research/tools/gen_universe.py from NSE's ind_nifty500list.csv on {today}; do not edit by hand.",
        "# Today's constituents only (survivorship bias, docs/data.md). Re-run at the semi-annual index reviews.",
        "name: nifty500",
        'index: "INDEX:NIFTY 500"',
        "symbols:",
    ]
    lines += [f"  - NSE:{symbol}" for symbol, _, _ in rows]
    lines.append("industry:")
    lines += [f'  "NSE:{symbol}": "{industry}"' for symbol, industry, _ in rows]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--csv", help="local ind_nifty500list.csv (default: download from NSE)")
    parser.add_argument("--instruments", help="local Kite NSE instrument dump (default: download)")
    parser.add_argument("--no-check", action="store_true", help="do not check symbols against the instrument dump")
    parser.add_argument("--out", default=OUT)
    args = parser.parse_args()

    rows = constituents(read(args.csv, NSE_CSV))
    if len(rows) < 450:
        sys.exit(f"only {len(rows)} constituents parsed; refusing to write {args.out}")
    if not args.no_check:
        known = tradable(read(args.instruments, KITE_NSE))
        missing = [symbol for symbol, _, _ in rows if symbol not in known]
        for symbol in missing:
            print(f"UNRESOLVED NSE:{symbol} is not an EQ instrument in the Kite dump", file=sys.stderr)
        print(f"{len(rows) - len(missing)} of {len(rows)} symbols resolve", file=sys.stderr)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(render(rows, datetime.date.today().isoformat()))
    print(f"wrote {args.out}: {len(rows)} symbols, {len({i for _, i, _ in rows})} industries", file=sys.stderr)


if __name__ == "__main__":
    main()
